# travis-ci.org build & test configuration
language: python

matrix:
    include:
        - python: 2.7
          env: PYTHON=2.7 ROOT=5.34.32
        - python: 2.7
          env: PYTHON=2.7 ROOT=6.04
        - python: 3.4
          env: PYTHON=3.4 ROOT=5.34.32
        - python: 3.4
          env: PYTHON=3.4 ROOT=6.04
    allow_failures:
        - python: 3.4

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi

  - export SWPATH=/software
  - sudo mkdir $SWPATH && sudo chown $USER $SWPATH
  - bash miniconda.sh -b -p $SWPATH/miniconda
  - export PATH="$SWPATH/miniconda/bin:$PATH"
  - export ENV_NAME=dps
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -q psutil
  - conda info -a # Useful for debugging any issues with conda
  - conda config --add channels http://conda.anaconda.org/NLeSC
  - conda config --set show_channel_urls yes
  - conda create -q -n ${ENV_NAME} python=${PYTHON} root=${ROOT} root-numpy numpy matplotlib nose sphinx pytables rootpy
  - export CONDA_ENV_PATH=$SWPATH/miniconda/envs/${ENV_NAME}
  - source activate ${ENV_NAME}
  - pip install -U uncertainties

script: bash ci/test.sh
cache: apt
