lumi = 10000
folder = '/storage/TopQuarkGroup/results/histogramfiles/2012_v9a'
#folder = '/storage/results/histogramfiles/AN-12-241_V3/PU_down'
#folder = '/storage/results/histogramfiles/AN-12-241_V3/PU_up'
identifier = 'PFElectron_PFMuon_PF2PATJets_PFMET'
#identifier = 'PFElectron_PFMuon_PF2PATJets_PFMET_PU_64600mb'
#identifier = 'PFElectron_PFMuon_PF2PATJets_PFMET_PU_71400mb'

files = {
    'SingleElectron':"%s/SingleElectron_%dpb_%s.root" % (folder, lumi, identifier),
    'SingleMu':"%s/SingleMu_%dpb_%s.root" % (folder, lumi, identifier),
    'TTJet' : "%s/TTJet_%dpb_%s.root" %(folder, lumi, identifier),
    'WJetsToLNu' : "%s/WJetsToLNu_%dpb_%s.root" %(folder, lumi, identifier),
    'W1Jet' : "%s/W1Jet_%dpb_%s.root" %(folder, lumi, identifier),
    'W2Jets' : "%s/W2Jets_%dpb_%s.root" %(folder, lumi, identifier),
    'W3Jets' : "%s/W3Jets_%dpb_%s.root" %(folder, lumi, identifier),
    'W4Jets' : "%s/W4Jets_%dpb_%s.root" %(folder, lumi, identifier),
    'DYJetsToLL' : "%s/DYJetsToLL_%dpb_%s.root" %(folder, lumi, identifier),
    'DY1JetsToLL' : "%s/DY1JetsToLL_%dpb_%s.root" %(folder, lumi, identifier),
    'DY2JetsToLL' : "%s/DY2JetsToLL_%dpb_%s.root" %(folder, lumi, identifier),
    'DY3JetsToLL' : "%s/DY3JetsToLL_%dpb_%s.root" %(folder, lumi, identifier),
    'DY4JetsToLL' : "%s/DY4JetsToLL_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_20_30_BCtoE' : "%s/QCD_Pt_20_30_BCtoE_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_30_80_BCtoE' : "%s/QCD_Pt_30_80_BCtoE_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_80_170_BCtoE' : "%s/QCD_Pt_80_170_BCtoE_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_170_250_BCtoE' : "%s/QCD_Pt_170_250_BCtoE_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_250_350_BCtoE' : "%s/QCD_Pt_250_350_BCtoE_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_350_BCtoE' : "%s/QCD_Pt_350_BCtoE_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_20_30_EMEnriched' : "%s/QCD_Pt_20_30_EMEnriched_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_30_80_EMEnriched' : "%s/QCD_Pt_30_80_EMEnriched_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_80_170_EMEnriched' : "%s/QCD_Pt_80_170_EMEnriched_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_170_250_EMEnriched' : "%s/QCD_Pt_170_250_EMEnriched_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_250_350_EMEnriched' : "%s/QCD_Pt_250_350_EMEnriched_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt_350_EMEnriched' : "%s/QCD_Pt_350_EMEnriched_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-20_MuEnrichedPt-15' : "%s/QCD_Pt_20_MuEnrichedPt_15_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-15to20_MuEnrichedPt5' : "%s/QCD_Pt-15to20_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-20to30_MuEnrichedPt5' : "%s/QCD_Pt-20to30_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-30to50_MuEnrichedPt5' : "%s/QCD_Pt-30to50_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-50to80_MuEnrichedPt5' : "%s/QCD_Pt-50to80_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-80to120_MuEnrichedPt5' : "%s/QCD_Pt-80to120_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-120to170_MuEnrichedPt5' : "%s/QCD_Pt-120to170_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-170to300_MuEnrichedPt5' : "%s/QCD_Pt-170to300_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-470to600_MuEnrichedPt5' : "%s/QCD_Pt-470to600_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-300to470_MuEnrichedPt5' : "%s/QCD_Pt-300to470_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
#    'QCD_Pt-600to800_MuEnrichedPt5' : "%s/QCD_Pt-600to800_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-800to1000_MuEnrichedPt5' : "%s/QCD_Pt-800to1000_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
    'QCD_Pt-1000_MuEnrichedPt5' : "%s/QCD_Pt-1000_MuEnrichedPt5_%dpb_%s.root" %(folder, lumi, identifier),
#    'pj1' : "%s/GJets_HT-40To100_%dpb_%s.root" %(folder, lumi, identifier),
#    'pj2' : "%s/GJets_HT-100To200_%dpb_%s.root" %(folder, lumi, identifier),
#    'pj3' : "%s/GJets_HT-200_%dpb_%s.root" %(folder, lumi, identifier),
     'GJets_HT-200To400' : "%s/GJets_HT-200To400_%dpb_%s.root" %(folder, lumi, identifier),
     'GJets_HT-400ToInf' : "%s/GJets_HT-400ToInf_%dpb_%s.root" %(folder, lumi, identifier),
#    'ww' : "%s/WWtoAnything_%dpb_%s.root" %(folder, lumi, identifier),
#    'wz' : "%s/WZtoAnything_%dpb_%s.root" %(folder, lumi, identifier),
#    'zz' : "%s/ZZtoAnything_%dpb_%s.root" %(folder, lumi, identifier),
    'T_tW-channel' : "%s/T_tW-channel_%dpb_%s.root" %(folder, lumi, identifier),
    'T_t-channel' : "%s/T_t-channel_%dpb_%s.root" %(folder, lumi, identifier),
    'T_s-channel' : "%s/T_s-channel_%dpb_%s.root" %(folder, lumi, identifier),
    'Tbar_tW-channel' : "%s/Tbar_tW-channel_%dpb_%s.root" %(folder, lumi, identifier),
    'Tbar_t-channel' : "%s/Tbar_t-channel_%dpb_%s.root" %(folder, lumi, identifier),
    'Tbar_s-channel' : "%s/Tbar_s-channel_%dpb_%s.root" %(folder, lumi, identifier),
#    'TTbarZIncl' : "%s/TTbarZIncl_%dpb_%s.root" %(folder, lumi, identifier),
#    'TTbarInclWIncl' : "%s/TTbarInclWIncl_%dpb_%s.root" %(folder, lumi, identifier),
             }
