#!/bin/bash
#A script for using make_CRAB_configuration.py to write CRAB configuration files for datasets specified in dataset_input.txt.
#
#It is recommended to run this script in the Configurations folder of NTupleTools, so that the created CRAB configuration files go into the correct locations/folders.
#If it is run from another location, any new folder(s) will be created in the working location, into which the created files will be placed, that is all.
#
#With current filepaths (as committed), make_CRAB_configuration.py should be in the same folder as this make_CRAB_configuration_from_file.sh script
#and das_client.py should be in the ../tools folder relative to this script.
#
#Simply run with: ./make_ntuples_CRAB_configurations.sh >&makentuplesconfigs.log &

#Data (LeptonPlus3Jets skim)
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012A-22Jan2013-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=600 --lumi_mask=Cert_190456-203742_8TeV_22Jan2013ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleElectron --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012B-22Jan2013-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_190456-203742_8TeV_22Jan2013ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleElectron --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012C-24Aug2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=200 --lumi_mask=Cert_198022-198523_8TeV_24Aug2012ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleElectron --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012C-PromptReco-v2/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_190456-208686_8TeV_PromptReco_Collisions12_JSON.txt --useData=1 --dataType=SingleElectron --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012C-EcalRecover_11Dec2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=40 --lumi_mask=Cert_201191-201191_8TeV_11Dec2012ReReco-recover_Collisions12_JSON.txt --useData=1 --dataType=SingleElectron --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012D-PromptReco-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=3000 --lumi_mask=Cert_190456-208686_8TeV_PromptReco_Collisions12_JSON.txt --useData=1 --dataType=SingleElectron --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012A-22Jan2013-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=500 --lumi_mask=Cert_190456-203742_8TeV_22Jan2013ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleMu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012B-22Jan2013-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=1500 --lumi_mask=Cert_190456-203742_8TeV_22Jan2013ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleMu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012C-24Aug2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=150 --lumi_mask=Cert_198022-198523_8TeV_24Aug2012ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleMu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012C-PromptReco-v2/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2400 --lumi_mask=Cert_190456-208686_8TeV_PromptReco_Collisions12_JSON.txt --useData=1 --dataType=SingleMu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012C-EcalRecover_11Dec2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=50 --lumi_mask=Cert_201191-201191_8TeV_11Dec2012ReReco-recover_Collisions12_JSON.txt     --useData=1 --dataType=SingleMu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012D-PromptReco-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2900 --lumi_mask=Cert_190456-208686_8TeV_PromptReco_Collisions12_JSON.txt --useData=1 --dataType=SingleMu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

#Data (Lepton skim)
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012A-13Jul2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_190456-196531_8TeV_13Jul2012ReReco_Collisions12_JSON_v2.txt --useData=1 --dataType=SingleElectron --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012A-recover-06Aug2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_190782-190949_8TeV_06Aug2012ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleElectron --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012B-13Jul2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_190456-196531_8TeV_13Jul2012ReReco_Collisions12_JSON_v2.txt --useData=1 --dataType=SingleElectron --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleElectron/Run2012C-24Aug2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_198022-198523_8TeV_24Aug2012ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleElectron --skim=Lepton --mail=None --whiteList=None --blackList=None

#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012A-13Jul2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_190456-196531_8TeV_13Jul2012ReReco_Collisions12_JSON_v2.txt --useData=1 --dataType=SingleMu --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012A-recover-06Aug2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_190782-190949_8TeV_06Aug2012ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleMu --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012B-13Jul2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_190456-196531_8TeV_13Jul2012ReReco_Collisions12_JSON_v2.txt --useData=1 --dataType=SingleMu --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/SingleMu/Run2012C-24Aug2012-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_198022-198523_8TeV_24Aug2012ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleMu --skim=Lepton --mail=None --whiteList=None --blackList=None

#Monte Carlo (LeptonPlus3Jets skim)
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TTJets_MassiveBinDECAY_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=TTJets --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TTJets_SemiLeptMGDecays_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A_ext-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=700 --lumi_mask=None --useData=0 --dataType=TTJets_SemiLeptMGDecays --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TTJets_FullLeptMGDecays_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v2/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=350 --lumi_mask=None --useData=0 --dataType=TTJets_FullLeptMGDecays --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TTJets_HadronicMGDecays_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A_ext-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=900 --lumi_mask=None --useData=0 --dataType=TTJets_HadronicMGDecays --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TT_8TeV-mcatnlo/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=900 --lumi_mask=None --useData=0 --dataType=TTJets --skim=LeptonPlus3Jets --isTTbarMC=1 --isMCatNLO=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TT_CT10_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v2/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=600 --lumi_mask=None --useData=0 --dataType=TTJets --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TT_Mtt-700to1000_CT10_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=90 --lumi_mask=None --useData=0 --dataType=TT_Mtt-700to1000_CT10 --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TT_Mtt-1000toInf_CT10_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=30 --lumi_mask=None --useData=0 --dataType=TT_Mtt-1000toInf_CT10 --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/T_t-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=100 --lumi_mask=None --useData=0 --dataType=T_t-channel_CT10 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/Tbar_t-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=Tbar_t-channel --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/T_s-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=5 --lumi_mask=None --useData=0 --dataType=T_s-channel --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/Tbar_s-channel_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=5 --lumi_mask=None --useData=0 --dataType=Tbar_s-channel --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/T_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=10 --lumi_mask=None --useData=0 --dataType=T_tW-channel --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/Tbar_tW-channel-DR_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=10 --lumi_mask=None --useData=0 --dataType=Tbar_tW-channel --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_20_30_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_20_30_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_30_80_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_30_80_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_80_170_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_80_170_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_170_250_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_170_250_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_250_350_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_250_350_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_350_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v2/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_350_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_20_30_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_20_30_EMEnriched --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_30_80_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_30_80_EMEnriched --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_80_170_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_80_170_EMEnriched --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_170_250_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_170_250_EMEnriched --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_250_350_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_250_350_EMEnriched --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_350_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_350_EMEnriched --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/GJets_HT-200To400_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1400 --lumi_mask=None --useData=0 --dataType=GJets_HT-200To400 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/GJets_HT-400ToInf_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=GJets_HT-400ToInf --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_20_MuEnrichedPt_15_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v3/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=500 --lumi_mask=None --useData=0 --dataType=QCD_Pt_20_MuEnrichedPt_15 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-15to20_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v2/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt-15to20_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-20to30_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=QCD_Pt-20to30_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-30to50_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=QCD_Pt-30to50_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-50to80_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=QCD_Pt-50to80_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-80to120_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=QCD_Pt-80to120_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-120to170_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=QCD_Pt-120to170_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-170to300_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=QCD_Pt-170to300_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-300to470_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=QCD_Pt-300to470_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-470to600_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=100 --lumi_mask=None --useData=0 --dataType=QCD_Pt-470to600_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-600to800_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=100 --lumi_mask=None --useData=0 --dataType=QCD_Pt-600to800_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-800to1000_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=100 --lumi_mask=None --useData=0 --dataType=QCD_Pt-800to1000_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt-1000_MuEnrichedPt5_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=100 --lumi_mask=None --useData=0 --dataType=QCD_Pt-1000_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=900 --lumi_mask=None --useData=0 --dataType=DYJetsToLL_M-50 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY1JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=700 --lumi_mask=None --useData=0 --dataType=DY1JetsToLL_M-50 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY2JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=600 --lumi_mask=None --useData=0 --dataType=DY2JetsToLL_M-50 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY3JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=DY3JetsToLL_M-50 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY4JetsToLL_M-50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=150 --lumi_mask=None --useData=0 --dataType=DY4JetsToLL_M-50 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY1JetsToLL_M-10To50_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=DY1JetsToLL_M-10to50 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY2JetsToLL_TuneZ2star_M-10To50_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=900 --lumi_mask=None --useData=0 --dataType=DY2JetsToLL_M-10to50 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=500 --lumi_mask=None --useData=0 --dataType=WJetsToLNu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball/Summer12_DR53X-PU_S10_START53_V7A-v2/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1500 --lumi_mask=None --useData=0 --dataType=WJetsToLNu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/W1JetsToLNu_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=700 --lumi_mask=None --useData=0 --dataType=W1Jet --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/W2JetsToLNu_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=W2Jets --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/W3JetsToLNu_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=400 --lumi_mask=None --useData=0 --dataType=W3Jets --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/W4JetsToLNu_TuneZ2Star_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=400 --lumi_mask=None --useData=0 --dataType=W4Jets --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TTJets_scaleup_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=150 --lumi_mask=None --useData=0 --dataType=TTJets-scaleup --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TTJets_scaledown_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=150 --lumi_mask=None --useData=0 --dataType=TTJets-scaledown --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TTJets_matchingup_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=150 --lumi_mask=None --useData=0 --dataType=TTJets-matchingup --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TTJets_matchingdown_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=150 --lumi_mask=None --useData=0 --dataType=TTJets-matchingdown --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TT_Mtt-700to1000_CT10_scaleup_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=TT_Mtt-700to1000_CT10_scaleup --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TT_Mtt-1000toInf_CT10_scaleup_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=30 --lumi_mask=None --useData=0 --dataType=TT_Mtt-1000toInf_CT10_scaleup --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TT_Mtt-700to1000_CT10_scaledown_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=TT_Mtt-700to1000_CT10_scaledown --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/TT_Mtt-1000toInf_CT10_scaledown_TuneZ2star_8TeV-powheg-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=30 --lumi_mask=None --useData=0 --dataType=TT_Mtt-1000toInf_CT10_scaledown --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/WJetsToLNu_scaleup_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v2/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=500 --lumi_mask=None --useData=0 --dataType=WJets-scaleup --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/WJetsToLNu_scaledown_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=500 --lumi_mask=None --useData=0 --dataType=WJets-scaledown --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/WJetsToLNu_matchingup_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=500 --lumi_mask=None --useData=0 --dataType=WJets-matchingup --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/WJetsToLNu_matchingdown_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=500 --lumi_mask=None --useData=0 --dataType=WJets-matchingdown --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/W1JetsToLNu_scaleup_TuneZ2Star_8TeV-madgraph/Summer12-START53_V7C_FSIM-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=400 --lumi_mask=None --useData=0 --dataType=W1Jets-scaleup --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/W1JetsToLNu_scaledown_TuneZ2Star_8TeV-madgraph/Summer12-START53_V7C_FSIM-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=400 --lumi_mask=None --useData=0 --dataType=W1Jets-scaledown --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/W1JetsToLNu_matchingup_TuneZ2Star_8TeV-madgraph/Summer12-START53_V7C_FSIM-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=400 --lumi_mask=None --useData=0 --dataType=W1Jets-matchingup --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/W1JetsToLNu_matchingdown_TuneZ2Star_8TeV-madgraph/Summer12-START53_V7C_FSIM-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=400 --lumi_mask=None --useData=0 --dataType=W1Jets-matchingdown --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DYJetsToLL_M-50_scaleup_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=ZJets-scaleup --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DYJetsToLL_M-50_scaledown_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=ZJets-scaledown --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DYJetsToLL_M-50_matchingup_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=ZJets-matchingup --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DYJetsToLL_M-50_matchingdown_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=ZJets-matchingdown --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY1JetsToLL_M-50_scaledown_8TeV-madgraph/Summer12-START53_V7C-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=Z1Jets-scaledown --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY1JetsToLL_M-50_scaleup_8TeV-madgraph/Summer12-START53_V7C-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=Z1Jets-scaleup --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY2JetsToLL_M-50_scaledown_8TeV-madgraph/Summer12-START53_V7C-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=Z2Jets-scaledown --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY2JetsToLL_M-50_scaleup_8TeV-madgraph/Summer12-START53_V7C-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=Z2Jets-scaleup --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY3JetsToLL_M-50_scaledown_8TeV-madgraph/Summer12-START53_V7C-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=Z3Jets-scaledown --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/DY3JetsToLL_M-50_scaleup_8TeV-madgraph/Summer12-START53_V7C-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=Z3Jets-scaleup --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

#Monte Carlo (Lepton Skim)
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_20_30_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=QCD_Pt_20_30_BCtoE --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_30_80_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=QCD_Pt_30_80_BCtoE --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_80_170_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=QCD_Pt_80_170_BCtoE --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_170_250_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=QCD_Pt_170_250_BCtoE --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_250_350_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=QCD_Pt_250_350_BCtoE --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_350_BCtoE_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v2/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=QCD_Pt_350_BCtoE --skim=Lepton --mail=None --whiteList=None --blackList=None

#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_20_30_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_20_30_EMEnriched --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_30_80_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_30_80_EMEnriched --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_80_170_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_80_170_EMEnriched --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_170_250_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_170_250_EMEnriched --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_250_350_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_250_350_EMEnriched --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_Pt_350_EMEnriched_TuneZ2star_8TeV_pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_350_EMEnriched --skim=Lepton --mail=None --whiteList=None --blackList=None

#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/GJets_HT-200To400_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1400 --lumi_mask=None --useData=0 --dataType=GJets_HT-200To400 --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/GJets_HT-400ToInf_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=GJets_HT-400ToInf --skim=Lepton --mail=None --whiteList=None --blackList=None

#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_HT-100To250_TuneZ2star_8TeV-madgraph-pythia/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_HT-100To250 --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_HT-250To500_TuneZ2star_8TeV-madgraph-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_HT-250To500 --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_HT-500To1000_TuneZ2star_8TeV-madgraph-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_HT-500To1000 --skim=Lepton --mail=None --whiteList=None --blackList=None
#python make_CRAB_configuration.py --jobtype=cmssw --scheduler=glite --use_server=1 --version=v10 --datasetpath=/QCD_HT-1000ToInf_TuneZ2star_8TeV-madgraph-pythia6/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=2000 --lumi_mask=None --useData=0 --dataType=QCD_HT-1000ToInf --skim=Lepton --mail=None --whiteList=None --blackList=None
